# possible values : production, development
app_mode = development

[paths]
# Path to where the data files can be created
datapath = .\

[server]
# The http port  to use
http_port = 8080

[security]
# secret = "shfKekNow68tGzUJD86T09wcZ2dLbOXsmxz5Kk7gcDshg1MTFDh4lcRVkYq+UjE7bzWyrH3zTLU2rnzEpEcvcA=="
